services:
  db:
    container_name: postgres
    image: postgres:16.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports: 
      - ${POSTGRES_PORT}:5432
    volumes:
      - type: bind
        source: ${POSTGRES_LOCAL_FOLDER}
        target: /var/lib/postgresql/data
    
  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
  
  redis:
    image: redis:alpine
    ports:
      - ${REDIS_PORT}:6379