"""add_Birthday

Revision ID: afbdf247ba09
Revises: f7879708250b
Create Date: 2024-04-11 18:40:41.625121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afbdf247ba09'
down_revision: Union[str, None] = 'f7879708250b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('birthday', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'birthday')
    # ### end Alembic commands ###
